/**
 * File generated by Magnet Magnet Lang Tool on Sep 17, 2015 10:54:22 AM
 * @see {@link http://developer.magnet.com}
 */
package com.magnet.smartshopper.wunderground;




import retrofit.http.*;
import com.magnet.smartshopper.wunderground.model.WeatherResponse;

public interface WeatherServiceClient {

  /**
   * 
   * GET /weatherservice/getcurrentweather
   */
  @GET("/api/d74d8ebc1cffe954/conditions/q/37.776289,-122.395234.json")
  WeatherResponse getCurrentWeather();

}
