/**
 * File generated by Magnet Magnet Lang Tool on Sep 17, 2015 10:54:22 AM
 * @see {@link http://developer.magnet.com}
 */

package com.magnet.smartshopper.wunderground.model;




public class WeatherResponse {


  private current_observation current_observation;



  public current_observation getCurrent_observation() {
    return current_observation;
  }
  public void setCurrent_observation(current_observation value) {
    this.current_observation = value;
  }

}
